// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace GloboTicket.Infrastructure.GloboTicket.Domain.CompiledModels
{
    public partial class GloboTicketContextModel
    {
        partial void Initialize()
        {
            var act = ActEntityType.Create(this);
            var show = ShowEntityType.Create(this);
            var ticketSale = TicketSaleEntityType.Create(this);
            var venue = VenueEntityType.Create(this);

            ShowEntityType.CreateForeignKey1(show, act);
            ShowEntityType.CreateForeignKey2(show, venue);
            TicketSaleEntityType.CreateForeignKey1(ticketSale, show);

            ActEntityType.CreateAnnotations(act);
            ShowEntityType.CreateAnnotations(show);
            TicketSaleEntityType.CreateAnnotations(ticketSale);
            VenueEntityType.CreateAnnotations(venue);

            AddAnnotation("ProductVersion", "6.0.2");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
