// <auto-generated />
using GloboTicket.Domain;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace GloboTicket.Infrastructure.GloboTicket.Domain.CompiledModels
{
    [DbContext(typeof(GloboTicketContext))]
    public partial class GloboTicketContextModel : RuntimeModel
    {
        static GloboTicketContextModel()
        {
            var model = new GloboTicketContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static GloboTicketContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
